# Generated by Django 6.0 on 2026-01-04 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('designation', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
